"""
Train a placement-probability classifier on the synthetic dataset.

Saves:
  - model_artifacts/placement_model.joblib   (trained XGBoost model)
  - model_artifacts/feature_columns.json     (canonical column order)
  - model_artifacts/metrics.json             (eval metrics on held-out test set)
  - model_artifacts/feature_importance.json  (global importances, for explainability)

Run: python ml/train.py
"""

import json
import sys
from pathlib import Path

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score, precision_score, recall_score, f1_score, brier_score_loss
import xgboost as xgb
import joblib

sys.path.append(str(Path(__file__).resolve().parent.parent))
from ml.features import build_features, feature_columns  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
DATA_PATH = ROOT / "data" / "synthetic_students.csv"
ARTIFACT_DIR = ROOT / "model_artifacts"
ARTIFACT_DIR.mkdir(exist_ok=True)


def main():
    df = pd.read_csv(DATA_PATH)

    X = build_features(df)[feature_columns()]
    y = df["placed"]

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42, stratify=y
    )

    model = xgb.XGBClassifier(
        n_estimators=200,
        max_depth=4,
        learning_rate=0.05,
        subsample=0.8,
        colsample_bytree=0.8,
        eval_metric="logloss",
        random_state=42,
    )
    model.fit(X_train, y_train)

    probs = model.predict_proba(X_test)[:, 1]
    preds = (probs >= 0.5).astype(int)

    metrics = {
        "roc_auc": round(roc_auc_score(y_test, probs), 4),
        "precision": round(precision_score(y_test, preds), 4),
        "recall": round(recall_score(y_test, preds), 4),
        "f1": round(f1_score(y_test, preds), 4),
        "brier_score": round(brier_score_loss(y_test, probs), 4),
        "n_train": len(X_train),
        "n_test": len(X_test),
        "base_rate_placed": round(float(y.mean()), 4),
        "note": (
            "Metrics are against held-out SYNTHETIC data generated by the same "
            "process as training data. High AUC here reflects that the model "
            "recovered the logistic function used to generate labels - it says "
            "nothing about real-world placement prediction accuracy."
        ),
    }

    joblib.dump(model, ARTIFACT_DIR / "placement_model.joblib")
    with open(ARTIFACT_DIR / "feature_columns.json", "w") as f:
        json.dump(feature_columns(), f, indent=2)
    with open(ARTIFACT_DIR / "metrics.json", "w") as f:
        json.dump(metrics, f, indent=2)

    importance = dict(
        zip(X.columns, [round(float(v), 4) for v in model.feature_importances_])
    )
    importance = dict(sorted(importance.items(), key=lambda kv: -kv[1]))
    with open(ARTIFACT_DIR / "feature_importance.json", "w") as f:
        json.dump(importance, f, indent=2)

    print(json.dumps(metrics, indent=2))
    print("\nTop 5 features by importance:")
    for k, v in list(importance.items())[:5]:
        print(f"  {k}: {v}")


if __name__ == "__main__":
    main()
