// DSP-BITS Handbook curriculum data.
// Source: DSP-BITS- Handbook.pdf, Data Stores & Pipeline, 3 credits.
// Dates are intentionally omitted because the handbook defines live-session
// weeks, not calendar dates; the tracker shows "Schedule from Lumen".
const DSP_BITS_COURSES = [
  {
    id: 'dsp',
    name: 'Data Stores & Pipeline',
    color: 'var(--sm-color)',
    bg: 'var(--sm-bg)',
    credits: '3 credits, 15 weeks',
    presenter: 'Dhanesh Salla',
    weeks: [
      { n: 1, label: '1', date: null, topic: 'Foundations of Data Storage Paradigms', caseStudy: 'Ride-sharing app', syllabus: ['Module introduction', 'File systems to RDBMS', 'Data warehouses and BI', 'Data lake to lakehouse', 'OLTP systems', 'OLAP workloads', 'OLTP vs OLAP use cases', 'Overview of RDBMS', 'Columnar databases explained', 'When to use what?', 'Deep dive into ACID', 'BASE and distributed systems', 'Ride-sharing app use case overview'] },
      { n: 2, label: '2', date: null, topic: 'Modern Data Warehousing', caseStudy: 'Financial services reporting and analytics', syllabus: ['Module introduction', 'What makes a warehouse modern?', 'Key functional features', 'Integrating with data lakes', 'What is MPP and why it matters', 'How queries are parallelized', 'Overview of Snowflake', 'Snowflake demo', 'Overview of Amazon Redshift', 'Redshift demo', 'Financial services reporting and analytics use case overview'] },
      { n: 3, label: '3', date: null, topic: 'Data Lakes and Lakehouse Foundations', caseStudy: 'Clickstream analytics for e-commerce', syllabus: ['Module introduction', 'What is a data lake?', 'What is a lakehouse?', 'Medallion architecture - bronze, silver, gold layers', 'Traditional CSV and its limitations', 'Introduction to Parquet and Avro', 'Format comparison and benchmarks', 'What is cloud object storage?', 'What is Spark?', 'Spark features and advantages', 'Clickstream analytics for e-commerce use case overview'] },
      { n: 4, label: '4', date: null, topic: 'Data Infrastructure in the Enterprise', caseStudy: 'Logistics company on AWS', syllabus: ['Module introduction', 'Data stack and its key components', 'Monolith to microservices', 'Distributed data processing', 'On-prem infrastructure', 'Cloud-native environments', 'Hybrid and multi-cloud', 'AWS data ecosystem', 'GCP data ecosystem', 'Azure data ecosystem', 'Logistics company on AWS use case overview'] },
      { n: 5, label: '5', date: null, topic: 'Modern Table Formats - Iceberg, Hudi, Delta Lake', caseStudy: "Uber's Apache Hudi", syllabus: ['Module introduction', 'Why modern table formats?', 'Overview: Iceberg', 'Overview: Delta Lake', 'Overview: Apache Hudi', 'Table format comparison matrix', 'Data storage in Spark', 'What is RDD and DataFrame?', 'Transformations and actions', 'Demo: transformations and actions', "Uber's Apache Hudi use case overview"] },
      { n: 6, label: '6', date: null, topic: 'Standard Data Pipeline Architecture', caseStudy: 'Online food delivery', syllabus: ['Module introduction', 'Batch ingestion', 'Micro-batch and real-time ingestion', 'Ingestion strategy comparison', 'What is CDC and why it matters', 'CDC tools and approaches', 'Lambda architecture', 'Kappa architecture', 'When to use what?', 'Introduction to event-driven architecture', 'Tools: Kafka, GCP Pub/Sub, AWS Kinesis', 'Online food delivery use case overview'] },
      { n: 7, label: '7', date: null, topic: 'Batch Data Ingestion', caseStudy: 'Resilient batch ingestion with PySpark', syllabus: ['Module introduction', 'Common file formats', 'Reading files using PySpark', 'Optimizing file reads', 'Demo: reading files using PySpark', 'JDBC-based ingestion using PySpark', 'Demo: reading RDBMS tables using PySpark', 'Calling REST APIs', 'Persisting API data', 'Demo: calling REST APIs using PySpark', 'Common validation rules', 'Error handling techniques', 'Resilient batch ingestion with PySpark use case overview'] },
      { n: 8, label: '8', date: null, topic: 'ELT vs. ETL Methodologies', syllabus: ['Module introduction', 'What is ETL?', 'What is ELT?', 'ETL architecture overview', 'ELT architecture with cloud data warehouses', 'ETL vs. ELT - which one and when?', 'ETL pipeline with PySpark - use case overview', 'Demo: building ETL with PySpark', 'ELT with dbt and Snowflake - use case overview', 'ELT with dbt and Snowflake - architecture overview'] },
      { n: 9, label: '9', date: null, topic: 'Data Transformation, Processing, and Data Quality', caseStudy: 'Retail banking pipeline', syllabus: ['Module introduction', 'Handling missing and null values', 'Outlier detection and removal', 'Data type casting and normalization', 'Different joins in Spark', 'Skew handling in joins', 'Partitioning for scalable joins', 'Defining quality metrics', 'Writing validation rules', 'Logging and alerting bad records', 'Overview of DQ frameworks', 'Retail banking pipeline use case overview'] },
      { n: 10, label: '10', date: null, topic: 'Streaming Data Ingestion', caseStudy: 'Twitter data pipeline', syllabus: ['Module introduction', 'Introduction to Kafka', 'Kafka architecture', 'Kafka fundamentals', 'Demo on writing a Kafka producer', 'Demo on writing a Kafka consumer to read messages', 'Introduction to Spark streaming concepts', 'Structured streaming API with Kafka integration', 'Transforming and outputting data to console/parquet', 'Twitter data pipeline use case overview'] },
      { n: 11, label: '11', date: null, topic: 'Orchestrating Data Pipelines with Apache Airflow', caseStudy: 'Marketing campaign orchestration', syllabus: ['Module introduction', 'What is orchestration?', 'Tools overview', 'What is Airflow?', 'Core concepts: DAGs, operators, tasks', 'Demo on writing a basic DAG', 'Advanced task features', 'Monitoring and debugging in Airflow UI', 'Marketing campaign orchestration use case overview'] },
      { n: 12, label: '12', date: null, topic: 'CI/CD Integration and Automation in Data Pipelines', caseStudy: 'CI/CD for data pipelines', syllabus: ['Module introduction', 'Git basics', 'GitHub for data projects', 'What is CI/CD in data engineering', 'Pipeline stages (build, test, deploy)', 'GitHub Actions', 'Jenkins and GitLab CI', 'When to use what', 'Unit testing with pytest', 'dbt tests for data quality', 'CI/CD for data pipelines use case overview'] },
      { n: 13, label: '13', date: null, topic: 'Data Governance, Security, and Monitoring in Data Pipelines', caseStudy: 'Securing PII in fintech pipelines', syllabus: ['Module introduction', 'What is data governance and why it matters', 'GDPR and CCPA overview', 'Engineering responsibilities under compliance', 'Data masking techniques', 'Encryption in data pipelines', 'Access control mechanisms', 'Metadata and governance', 'Lineage: the audit trail of data', 'Tools for metadata and lineage', 'Why monitoring pipelines is critical', 'Prometheus for metric collection', 'Grafana dashboards and alerts', 'Securing PII in fintech pipelines use case overview'] },
      { n: 14, label: '14-15', date: null, topic: 'Comprehensive examination', syllabus: ['Comprehensive examination'] }
    ]
  }
];

const DSP_BITS_DEADLINES = [
  { date: null, title: 'Comprehensive examination', sub: 'Handbook Weeks 14-15' }
];
